/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "include/libyuv.h"
#include <android/log.h>
/* Header for class com_wpf_library_libyuv_android_YUVUtils */

#ifndef _Included_com_wpf_library_libyuv_android_YUVUtils
#define _Included_com_wpf_library_libyuv_android_YUVUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_HashDjb2
 * Signature: ([BJI)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1HashDjb2
  (JNIEnv *, jclass, jbyteArray, jlong, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_ARGBDetect
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1ARGBDetect
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_ComputeSumSquareError
 * Signature: ([B[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1ComputeSumSquareError
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_ComputeSumSquareErrorPlane
 * Signature: ([BI[BIII)J
 */
JNIEXPORT jlong JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1ComputeSumSquareErrorPlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_SumSquareErrorToPsnr
 * Signature: (JJ)J
 */
JNIEXPORT jdouble JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1SumSquareErrorToPsnr
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_CalcFramePsnr
 * Signature: ([BI[BIII)J
 */
JNIEXPORT jdouble JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1CalcFramePsnr
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_I420Psnr
 * Signature: ([BI[BI[BI[BI[BI[BIII)J
 */
JNIEXPORT jdouble JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1I420Psnr
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_CalcFrameSsim
 * Signature: ([BI[BIII)J
 */
JNIEXPORT jdouble JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1CalcFrameSsim
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Compare_I420Ssim
 * Signature: ([BI[BI[BI[BI[BI[BIII)J
 */
JNIEXPORT jdouble JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Compare_1I420Ssim
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_I420Copy
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1I420Copy
        (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint,
         jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_I422ToI420
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1I422ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_I444ToI420
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1I444ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_I400ToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1I400ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_NV12ToI420
 * Signature: ([BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1NV12ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_NV21ToI420
 * Signature: ([BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1NV21ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_M420ToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1M420ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_YUY2ToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1YUY2ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_UYVYToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1UYVYToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGBToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGBToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_BGRAToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1BGRAToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ABGRToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ABGRToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_RGBAToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1RGBAToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_RGB24ToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1RGB24ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_RAWToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1RAWToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_RGB565ToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1RGB565ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB1555ToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB1555ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB4444ToI420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB4444ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_Android420ToI420
 * Signature: ([BI[BI[BII[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1Android420ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_ARGBCopy
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1ARGBCopy
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I420ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I420ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I420ToABGR
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I420ToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_J420ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1J420ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_J420ToABGR
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1J420ToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_H420ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1H420ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_H420ToABGR
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1H420ToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I422ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I422ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I422ToABGR
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I422ToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_J422ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1J422ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_J422ToABGR
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1J422ToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_H422ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1H422ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_H422ToABGR
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1H422ToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I444ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I444ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I444ToABGR
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I444ToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_J444ToARGB
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1J444ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I420AlphaToARGB
 * Signature: ([BI[BI[BI[BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I420AlphaToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I420AlphaToABGR
 * Signature: ([BI[BI[BI[BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I420AlphaToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_I400ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1I400ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_J400ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1J400ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_BGRAToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1BGRAToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_ARGBToBGRA
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1ARGBToBGRA
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_ABGRToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1ABGRToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_ARGBToABGR
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1ARGBToABGR
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_RGBAToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1RGBAToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_RGB24ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1RGB24ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_RAWToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1RAWToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_RGB565ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1RGB565ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_ARGB1555ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1ARGB1555ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_ARGB4444ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1ARGB4444ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_NV12ToARGB
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1NV12ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_NV21ToARGB
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1NV21ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_M420ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1M420ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_YUY2ToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1YUY2ToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_ARGB_UYVYToARGB
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1ARGB_1UYVYToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToI422
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToI422
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToI444
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToI444
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I400Copy
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I400Copy
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I422ToYUY2
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I422ToYUY2
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToYUY2
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToYUY2
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I422ToUYVY
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I422ToUYVY
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToUYVY
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToUYVY
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToNV12
 * Signature: ([BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToNV12
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToNV21
 * Signature: ([BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToNV21
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToRGBA
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToRGBA
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToBGRA
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToBGRA
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToRGB24
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToRGB24
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToRAW
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToRAW
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToARGB1555
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToARGB1555
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToARGB4444
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToARGB4444
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToRGB565
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToRGB565
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_I420ToRGB565Dither
 * Signature: ([BI[BI[BI[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1I420ToRGB565Dither
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ConvertFromI420
 * Signature: ([BI[BI[BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ConvertFromI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToI444
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToI444
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToI422
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToI422
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToNV12
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToNV12
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToNV21
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToNV21
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToYUY2
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToYUY2
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToUYVY
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToUYVY
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToI400
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToI400
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToRGBA
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToRGBA
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToRGB24
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToRGB24
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToRAW
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToRAW
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToRGB565Dither
 * Signature: ([BI[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToRGB565Dither
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToRGB565
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToRGB565
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToARGB1555
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToARGB1555
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToARGB4444
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToARGB4444
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToJ420
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToJ420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToJ422
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToJ422
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_From_ARGB_ARGBToJ400
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1From_1ARGB_1ARGBToJ400
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_To_ARGB_ConvertToARGB
 * Signature: ([BI[BIIIIIIILcom/wpf/library/libyuv_android/Data/RotationMode;I)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1To_1ARGB_1ConvertToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Convert_To_I420_ConvertToI420
 * Signature: ([BI[BI[BI[BIIIIIIILcom/wpf/library/libyuv_android/Data/RotationMode;I)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Convert_1To_1I420_1ConvertToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_CopyPlane
 * Signature: ([BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1CopyPlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_CopyPlane_16
 * Signature: ([SI[SIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1CopyPlane_116
  (JNIEnv *, jclass, jshortArray, jint, jshortArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I422Copy
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I422Copy
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I444Copy
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I444Copy
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I400ToI400
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I400ToI400
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I420ToI400
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I420ToI400
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_SplitUVPlane
 * Signature: ([BI[BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1SplitUVPlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_MergeUVPlane
 * Signature: ([BI[BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1MergeUVPlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_YUY2ToI422
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1YUY2ToI422
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_UYVYToI422
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1UYVYToI422
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_YUY2ToY
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1YUY2ToY
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I400Mirror
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I400Mirror
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I420Mirror
 * Signature: ([BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I420Mirror
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBMirror
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBMirror
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBBlend
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBBlend
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_BlendPlane
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1BlendPlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I420Blend
 * Signature: ([BI[BI[BI[BI[BI[BI[BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I420Blend
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBMultiply
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBMultiply
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBAdd
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBAdd
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBSubtract
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBSubtract
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I422ToRGBA
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I422ToRGBA
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I422ToBGRA
 * Signature: ([BI[BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I422ToBGRA
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_NV12ToRGB565
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1NV12ToRGB565
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_RAWToRGB24
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1RAWToRGB24
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_SetPlane
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1SetPlane
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I420Rect
 * Signature: ([BI[BI[BIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I420Rect
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBRect
 * Signature: ([BIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBRect
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBAttenuate
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBAttenuate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBUnattenuate
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBUnattenuate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBGrayTo
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBGrayTo
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBGray
 * Signature: ([BIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBGray
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBSepia
 * Signature: ([BIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBSepia
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBColorMatrix
 * Signature: ([BI[BILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBColorMatrix
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_RGBColorMatrix
 * Signature: ([BILjava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1RGBColorMatrix
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBColorTable
 * Signature: ([BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBColorTable
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_RGBColorTable
 * Signature: ([BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1RGBColorTable
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBQuantize
 * Signature: ([BIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBQuantize
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBComputeCumulativeSum
 * Signature: ([BI[IIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBComputeCumulativeSum
  (JNIEnv *, jclass, jbyteArray, jint, jintArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBBlur
 * Signature: ([BI[BI[IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBBlur
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jintArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBShade
 * Signature: ([BI[BIII[I)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBShade
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_InterpolatePlane
 * Signature: ([BI[BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1InterpolatePlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBInterpolate
 * Signature: ([BI[BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBInterpolate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_I420Interpolate
 * Signature: ([BI[BI[BI[BI[BI[BI[BI[BI[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1I420Interpolate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBShuffle
 * Signature: ([BI[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBShuffle
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBSobel
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBSobel
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBSobelToPlane
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBSobelToPlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBSobelXY
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBSobelXY
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBPolynomial
 * Signature: ([BI[BI[FII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBPolynomial
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jfloatArray, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_HalfFloatPlane
 * Signature: ([SI[SIFII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1HalfFloatPlane
  (JNIEnv *, jclass, jshortArray, jint, jshortArray, jint, jfloat, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBLumaColorTable
 * Signature: ([BI[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBLumaColorTable
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBCopyAlpha
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBCopyAlpha
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBExtractAlpha
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBExtractAlpha
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_ARGBCopyYToAlpha
 * Signature: ([BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1ARGBCopyYToAlpha
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_YUY2ToNV12
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1YUY2ToNV12
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Planar_functions_UYVYToNV12
 * Signature: ([BI[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Planar_1functions_1UYVYToNV12
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_TransposePlane
 * Signature: ([BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1TransposePlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_RotatePlane90
 * Signature: ([BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1RotatePlane90
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_RotatePlane270
 * Signature: ([BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1RotatePlane270
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_RotatePlane180
 * Signature: ([BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1RotatePlane180
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_TransposeUV
 * Signature: ([BI[BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1TransposeUV
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_RotateUV90
 * Signature: ([BI[BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1RotateUV90
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_RotateUV270
 * Signature: ([BI[BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1RotateUV270
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_RotateUV180
 * Signature: ([BI[BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1RotateUV180
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_RotatePlane
 * Signature: ([BI[BIIILcom/wpf/library/libyuv_android/Data/RotationMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1RotatePlane
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_I420Rotate
 * Signature: ([BI[BI[BI[BI[BI[BIIILcom/wpf/library/libyuv_android/Data/RotationMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1I420Rotate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_NV12ToI420Rotate
 * Signature: ([BI[BI[BI[BI[BIIILcom/wpf/library/libyuv_android/Data/RotationMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1NV12ToI420Rotate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Rotate_ARGB_ARGBRotate
 * Signature: ([BI[BIIILcom/wpf/library/libyuv_android/Data/RotationMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Rotate_1ARGB_1ARGBRotate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_ScalePlane
 * Signature: ([BIII[BIIILcom/wpf/library/libyuv_android/Data/FilterMode;)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1ScalePlane
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_ScalePlane_16
 * Signature: ([SIII[SIIILcom/wpf/library/libyuv_android/Data/FilterMode;)V
 */
JNIEXPORT void JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1ScalePlane_116
  (JNIEnv *, jclass, jshortArray, jint, jint, jint, jshortArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_I420Scale
 * Signature: ([BI[BI[BIII[BI[BI[BIIILcom/wpf/library/libyuv_android/Data/FilterMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1I420Scale
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_I420Scale_16
 * Signature: ([SI[SI[SIII[SI[SI[SIIILcom/wpf/library/libyuv_android/Data/FilterMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1I420Scale_116
  (JNIEnv *, jclass, jshortArray, jint, jshortArray, jint, jshortArray, jint, jint, jint, jshortArray, jint, jshortArray, jint, jshortArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_Scale
 * Signature: ([B[B[BIIIII[B[B[BIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1Scale
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_ScaleOffset
 * Signature: ([BII[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1ScaleOffset
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_ARGB_ARGBScaleClip
 * Signature: ([BIII[BIIIIIIILcom/wpf/library/libyuv_android/Data/FilterMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1ARGB_1ARGBScaleClip
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_ARGB_ARGBScale
 * Signature: ([BIII[BIIILcom/wpf/library/libyuv_android/Data/FilterMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1ARGB_1ARGBScale
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_wpf_library_libyuv_android_YUVUtils
 * Method:    Scale_ARGB_YUVToARGBScaleClip
 * Signature: ([BI[BI[BIIII[BIIIIIIIILcom/wpf/library/libyuv_android/Data/FilterMode;)I
 */
JNIEXPORT jint JNICALL Java_com_wpf_library_libyuv_1android_YUVUtils_Scale_1ARGB_1YUVToARGBScaleClip
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint, jobject);


JNIEXPORT libyuv::FilterMode JNICALL getFilterMode(JNIEnv * env, jobject filtering);

JNIEXPORT libyuv::RotationMode JNICALL getRotationMode(JNIEnv * env, jobject rotationMode);

#ifdef __cplusplus
}
#endif
#endif
